### ISSUE TITLE
Add MaybeCollect to return Option<T> similar to fold1

### ISSUE THREAD

**Issue by iopq** [bluss/rust-itertools#184]
I saw some code that went like

```
trait MaybeCollect: Iterator {
    fn maybe_collect<B>(self) -> Option<B> where B: FromIterator<Self::Item>;
}

impl<T> MaybeCollect for T where T: Iterator {
    fn maybe_collect<B>(self) -> Option<B> where B: FromIterator<Self::Item> {
        let mut iter = self.peekable();
        if iter.peek().is_none() {
            None
        } else {
            Some(iter.collect())
        }
    }
}
```

I liked the idea, because it would let me simplify some code where I use `.fold1(MyTrait::concatenate)` from itertools by instead using `.maybe_collect::T()` which would be shorter since it doesn't require me to introduce a trait to allow all the different types to be folded.

**Comment by bluss** [comment]
I'm not convinced. It can be a good function, doesn't need to be a trait?

**Comment by iopq** [comment]
So here's the function I would use it in:

	fn accumulate<'a, T>(tuples: &[(&'a str, &Fn(i32) -> bool)], i: i32) -> T
			where T: FromIterator<&'a str> + From<String> {

		tuples.iter()
			.filter(apply(second, i))
			.map(first)
			.cloned()
			.maybe_collect::<T>()
			.unwrap_or_else(|| i.to_string().into())
	}

how would this be written using just a free function instead of a trait?

**Comment by bluss** [comment]
just something like this works:

```rust
fn maybe_collect<I, C>(iterable: I) -> C where I: IntoIterator, C: FromIterator<I::Item> { }
```

**Comment by iopq** [comment]
Obviously that should be `Option<C>`, but if you write it this way you can't chain it like in my code. You'd have to write:

    maybe_collect(
	tuples.iter()
		.filter(apply(second, i))
		.map(first)
		.cloned())
		.unwrap_or_else(|| i.to_string().into())

**Comment by bluss** [comment]
I'm sorry, we're just going to go with not including this, I'll use some maintainer discretion.

I'm uncomfortable with it because putting a peekable in there will have the rest of the collect perform   worse, which is not an intuitive part of the abstraction. fold1 does not have this problem, because it delegates to the underlying fold after picking off a single element.

This is probably a silly concern. But sometimes people turn around and say “you said iterators in rust perform excellent” and then we pay for the small abstractions like this.
